### ISSUE TITLE
JOSS paper

### ISSUE THREAD

**Issue by brandondube** [QITI/pySLM2#16]
This issue is part of my JOSS review at https://github.com/openjournals/joss-reviews/issues/6315

The review criteria for the paper are

- [ ] Summary: Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?

The current draft of the paper can be outlined as follows

- holographic beam shaping with SLMs
- summary of pySLM2 (one sentence)
- technical detail on hologram algorithms (related, #15)
- tensorflow / gpus (related, #13)
- universal* interface to two SLM/DMD vendors' devices

I struggle with the `...diverse, non-specialist audience` portion of the criteria.  I also feel that the summary does not really "summarize" the software.  The one sentence is

> pySLM2 is a python package designed for full-stack control of SLMs for holographic beam
shaping, encompassing hologram generation, simulation, and hardware controls.

full-stack is not defined, one can maybe infer that it has something to do with both hardware control and (?) portion of software from the closing paragraph about universal control.  Spending this morning rummaging in your code, perhaps "summary" could/should touch on:

- the software can simulate the far-field / fourier plane of a DMD or SLM device
- the software can compute a command to apply to a DMD/SLM to achieve a given far-field complex E-field, given the field incident on the DMD/SLM
- likewise, the software can compute the command to generate a specific aberration correction
- the software includes numerous common decompositions in optics (HG, LG, SG, Zernike, ...)
- the software includes an abstraction of DMD/SLM vendor APIs, providing a universal interface to apply computed commands to hardware

- [ ] A statement of need: Does the paper have a section titled 'Statement of need' that clearly states what problems the software is designed to solve, who the target audience is, and its relation to other work?

Missing `...and its relation to other work?`

- [ ] State of the field: Do the authors describe how this software compares to other commonly-used packages?

no

- [x] Quality of writing: Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?

- [x] References: Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax](https://pandoc.org/MANUAL.html#extension-citations)?

**Comment by ldes89150** [comment]
>  A statement of need: Does the paper have a section titled 'Statement of need' that clearly states what problems the software is designed to solve, who the target audience is, and its relation to other work?
> 
> Missing ...and its relation to other work?
> 
>  State of the field: Do the authors describe how this software compares to other commonly-used packages?
> no

Addressed in #25

**Comment by brandondube** [comment]
I have read the current draft of the paper.  Overall, it is much improved - thank you!  A few areas I would request improvement:

> ... It has been shown that residual aberrations can be corrected to less than 𝜆/20 root-mean-square (RMS) which is smaller than most of the manufacturing tolerances of optical elements.

This is not really true.  For example, a "standard" off-the-shelf lens is finished to an irregularity of a quarter wave PV (quoted) and more like lambda/5 to 6 PV if you actually do incoming inspection of the components.  With the rule of thumb that RMS ~ 1/4 to 1/5 of PV, lambda/20 RMS is about as good as a "standard" off the shelf component, and worse than a "precision" or "high precision" component.  I think it would serve your purpose better to say `...lambda/20, which satisfies the Maréchal criteria`, which nobody can argue with

Your paper now features a brief survey of other SLM related packages on github, which is good.  However, I do not think it does an adequate job of relating the package to other works; it reads as though you did a search on Github, and listed approximately the first sentence about each package you found.  For example, CGH-diff also uses tensorflow, and so in the same way that your library supports CPU or GPU, so does that one.  You highlight a few features your library has,

1. Support for multiple (sic: two) vendors
2. Multiple algorithms
3. The user can view the far-field pattern of the hologram with your library
4. You have GPU acceleration

Regarding (1), I find it strained to say that two vendors "contrasts" to one when comparing to the other works in the field.  r.e (3), this is possible with all of the other libraries you referenced, and item (4) is a feature of 2/3 of the libraries you referenced.  These seem to be largely non-distinguishing features.

Your library is not required to be completely unique, filling a niche no other library does, but I think you should do a better job noting that most of the other libraries in the field are rather comparable.

**Comment by brandondube** [comment]
I am satisfied with the changes to the manuscript
