### ISSUE TITLE
Luxbeam missing in docs for utils

### ISSUE THREAD

**Issue by wavefrontshaping** [QITI/pySLM2#20]
This issue is part of my JOSS review at https://github.com/openjournals/joss-reviews/issues/6315

In the built docs as well as in the online docs, the `utils` section does not mention the `Luxbeam` controller that is used in one example.

**Comment by ldes89150** [comment]
The API for the Luxbeam controller is here:

https://pyslm2.pages.dev/pySLM2.util#pySLM2.util.controller.LuxbeamController

I will link the example to the doc building process.

**Comment by ldes89150** [comment]
Example for the `LuxbeamController` 

https://pyslm2.pages.dev/examples#load-image-to-the-luxbeam-dmd-controller
